### ISSUE TITLE
Cannot open Radar

### ISSUE THREAD

**Issue by skeremeke** [Slothfulwave612/soccerplots#1]
I have this error while i try to import module.
`AttributeError: module 'soccerplots' has no attribute 'radar_chart'`

**Comment by slothfulwave** [comment]
I think you dont have the latest version of soccerplots. The latest version is `1.0.0`

You can check the version by running the following line:

```
import soccerplots
soccerplots.__version__
```

To update you can use(in your terminal): `pip install soccerplots --upgrade`
